### ISSUE TITLE
Missing Argument Passed to Drupal\metatag\Command\GenerateGroupCommand::__construct()

### ISSUE THREAD

**Issue by dsdobrzynski** [hechoendrupal/drupal-console#2877]
With a clean install of  the latest dev version of metatag (9d0ec8e682d9500ce5e4e7bb6f09d2d82e4c77b6), the latest dev version of config_split (97d238714286e59b1f9881d8164442c0f170599a), and DrupalConsole 1.0.0-beta5, I am getting the following error when running the command config_split:export:

```
TypeError: Argument 1 passed to Drupal\metatag\Command\GenerateGroupCommand::__construct() must be an instance of Drupal\metatag\Generator\MetatagGroupGenerator, none given in /var/www/html/modules/contrib/metatag/src/Command/GenerateGroupCommand.php on line 56 #0 [internal function]: Drupal\metatag\Command\GenerateGroupCommand->__construct()
#1 /var/www/vendor/drupal/console/src/Helper/CommandDiscoveryHelper.php(282): ReflectionClass->newInstance()
#2 /var/www/vendor/drupal/console/src/Helper/CommandDiscoveryHelper.php(220): Drupal\Console\Helper\CommandDiscoveryHelper->validateCommand('Drupal\\metatag\\...', 'metatag', 'module')
#3 /var/www/vendor/drupal/console/src/Helper/CommandDiscoveryHelper.php(159): Drupal\Console\Helper\CommandDiscoveryHelper->extractCommands('/var/www/html/m...', 'metatag', 'module')
#4 /var/www/vendor/drupal/console/src/Helper/CommandDiscoveryHelper.php(117): Drupal\Console\Helper\CommandDiscoveryHelper->discoverCommands(Array)
#5 /var/www/vendor/drupal/console/src/Helper/CommandDiscoveryHelper.php(75): Drupal\Console\Helper\CommandDiscoveryHelper->getCustomCommands()
#6 /var/www/vendor/drupal/console/src/Application.php(312): Drupal\Console\Helper\CommandDiscoveryHelper->getCommands()
#7 /var/www/vendor/drupal/console/src/Application.php(245): Drupal\Console\Application->prepare(Object(Drupal\Console\Helper\DrupalHelper), 'config_split:ex...')
#8 /var/www/vendor/symfony/console/Application.php(124): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#9 /var/www/vendor/drupal/console/bin/drupal.php(115): Symfony\Component\Console\Application->run()
#10 /var/www/vendor/drupal/console/bin/drupal(4): require('/var/www/vendor...')
#11 {main}
TypeError: Argument 1 passed to Drupal\metatag\Command\GenerateGroupCommand::__construct() must be an instance of Drupal\metatag\Generator\MetatagGroupGenerator, none given in Drupal\metatag\Command\GenerateGroupCommand->__construct() (line 56 of /var/www/html/modules/contrib/metatag/src/Command/GenerateGroupCommand.php).
```

Exporting all config through the core Config UI works fine.

**Comment by jmolivas** [comment]
@dsdobrzynski try updating to latest DrupalConsole and DrupalConsole Launcher (if installed) https://gist.github.com/jmolivas/a0970e1ea252ecb852fe8c7182d85d3e

**Comment by dsdobrzynski** [comment]
@jmolivas Thanks for the fast response and sorry for the delay.

I tried using `1.0.0-rc8`, `master`, and `develop`. After modifying the version in `composer.json`, I ran:
```
composer update drupal/console
composer install
drupal config_split:export
```
All versions resulted in the error:
`[ERROR] Command "config_split:export", is not a valid command name.`

**Comment by harold20** [comment]
This issue is not longer present in the current version 1.8.0
