### ISSUE TITLE
[generate:profile] add an option to specify enabled themes

### ISSUE THREAD

**Issue by ao2** [hechoendrupal/drupal-console#3092]
The `--dependencies` option tells what modules put as dependencies in the profile .info.yml file.

However this is not enough to have a profile which installs cleanly in the case where configuration has also been exported, because the config files also refer to themes.

Steps to reproduce:

* get the list of the enabled modules with:
  ```
  ENABLED_MODULES="$(drush pm-list --type=module --status=enabled --pipe | tr '\n' ',')"
  ```

* generate a profile with `generate:profile --dependencies=$ENABLED_MODULES` and copy it somewhere else;
* export the config with `export:config --remove-uuid --remove-config-hash` and copy it to the profile from above, in the `config/install` dir, removing `core.extension.yml` as suggested in https://www.drupal.org/docs/8/creating-distributions/how-to-write-a-drupal-8-installation-profile
* try to install a new site with the profile from above

In this scenario an error like this is triggered at install time:

```
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                        [ok]
Drupal\Core\Config\UnmetDependenciesException: Configuration objects (block.block.bartik_account_menu, block.block.bartik_branding,                 [error]
block.block.bartik_breadcrumbs, block.block.bartik_content, block.block.bartik_footer, block.block.bartik_help, block.block.bartik_local_actions,
block.block.bartik_local_tasks, block.block.bartik_main_menu, block.block.bartik_messages, block.block.bartik_page_title,
block.block.bartik_powered, block.block.bartik_search, block.block.bartik_tools, block.block.languageswitcher, block.block.seven_breadcrumbs,
block.block.seven_content, block.block.seven_help, block.block.seven_local_actions, block.block.seven_login, block.block.seven_messages,
block.block.seven_page_title, block.block.seven_primary_local_tasks, block.block.seven_secondary_local_tasks, seven.settings) provided by
pathauto_bulk_generate_test_profile2 have unmet dependencies in
.../web/core/lib/Drupal/Core/Config/UnmetDependenciesException.php:84
Stack trace:
#0 .../web/core/lib/Drupal/Core/Config/ConfigInstaller.php(460):
Drupal\Core\Config\UnmetDependenciesException::create('pathauto_bulk_g...', Array)
#1 .../web/core/lib/Drupal/Core/ProxyClass/Config/ConfigInstaller.php(132):
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'pathauto_bulk_g...')
#2 .../web/core/lib/Drupal/Core/Extension/ModuleInstaller.php(141):
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'pathauto_bulk_g...')
#3 .../web/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#4 .../web/core/includes/install.core.inc(1555): Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, false)
#5 .../web/core/includes/install.core.inc(660): install_install_profile(Array)
#6 .../web/core/includes/install.core.inc(538): install_run_task(Array, Array)
#7 .../web/core/includes/install.core.inc(115): install_run_tasks(Array)
#8 .../vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#9 .../vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#10 .../vendor/drush/drush/commands/core/drupal/site_install.inc(80): drush_op('install_drupal',
Object(Composer\Autoload\ClassLoader), Array)
#11 .../vendor/drush/drush/commands/core/site_install.drush.inc(249): drush_core_site_install_version('pathauto_bulk_g...',
Array)
#12 .../vendor/drush/drush/includes/command.inc(422): drush_core_site_install('pathauto_bulk_g...')
#13 .../vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#14 .../vendor/drush/drush/includes/command.inc(199): drush_command('pathauto_bulk_g...')
#15 .../vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#16 .../vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#17 .../vendor/drush/drush/drush.php(12): drush_main()
#18 {main}
Command dispatch complete
```

This goes away if the enabled themes are listed in the .info.yml file too, like:

```
themes:
  - bartik
  - seven
```

Would it be possible to add a `--themes` option to pass the themes too to `[generate:profile]`, just like `--dependencies`?

Thanks,
   Antonio

**Comment by ao2** [comment]
OK, I am looking at adding the `--themes` option myself, by generalizing the `checkDependencies()` mechanism into a more generic `checkExtensions()` and reusing it to validate the arguments to the new option.

I'll post an update when I got something working.

Ciao,
   Antonio

**Comment by ao2** [comment]
Hi,

during the refactoring I am considering moving the `checkExtension` function into `ExtensionManager` and that would mean make the latter depend on `http_client'; I tried this approach:

```
diff --git a/services-drupal-install.yml b/services-drupal-install.yml
index 015cb4b6..8e4a50d0 100644
--- a/services-drupal-install.yml
+++ b/services-drupal-install.yml
@@ -4,7 +4,7 @@ services:
     arguments: ['@app.root']
   console.extension_manager:
     class: Drupal\Console\Extension\Manager
-    arguments: ['@console.site', '@app.root']
+    arguments: ['@console.site', '@http_client', '@app.root']
   console.server:
     class: Drupal\Console\Command\ServerCommand
     arguments: ['@app.root', '@console.configuration_manager']
diff --git a/src/Extension/Manager.php b/src/Extension/Manager.php
index 6c977d74..6e18dc70 100644
--- a/src/Extension/Manager.php
+++ b/src/Extension/Manager.php
@@ -3,6 +3,8 @@
 namespace Drupal\Console\Extension;

 use Drupal\Console\Utils\Site;
+use GuzzleHttp\Client;
+use GuzzleHttp\Exception\ClientException;

 /**
  * Class ExtensionManager
@@ -15,6 +17,12 @@ class Manager
      * @var Site
      */
     protected $site;
+
+    /**
+     * @var Client
+     */
+    protected $httpClient;
+
     /**
      * @var string
      */
@@ -39,13 +47,16 @@ class Manager
      * ExtensionManager constructor.
      *
      * @param Site   $site
+     * @param Client $httpClient
      * @param string $appRoot
      */
     public function __construct(
         Site $site,
+        Client $httpClient,
         $appRoot
     ) {
         $this->site = $site;
+        $this->httpClient = $httpClient;
         $this->appRoot = $appRoot;
         $this->initialize();
     }
```

But it fails here with this error (drupal console master + drupal 8.2.5):

```
$ ./bin/drupal generate:profile '--profile=Test Profile' --machine-name=pathauto_bulk_generate_test_profile2 --dependencies=node,block,dblog,page_cache,dynamic_page_cache '--description=Test Profile' --no-interaction
TypeError: Argument 2 passed to Drupal\Core\Http\HandlerStackConfigurator::__construct() must be of the type array, none given in .../web/core/lib/Drupal/Core/Http/HandlerStackConfigurator.php on line 53 #0 [internal function]: Drupal\Core\Http\HandlerStackConfigurator->__construct(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#1 .../vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 .../vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'http_handler_st...')
#3 .../vendor/symfony/dependency-injection/ContainerBuilder.php(954): Symfony\Component\DependencyInjection\ContainerBuilder->get('http_handler_st...', 1)
#4 .../vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'http_handler_st...')
#5 .../vendor/symfony/dependency-injection/ContainerBuilder.php(985): Symfony\Component\DependencyInjection\ContainerBuilder->get('http_handler_st...', 1)
#6 .../vendor/symfony/dependency-injection/ContainerBuilder.php(982): Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices(Object(Symfony\Component\DependencyInjection\Reference))
#7 .../vendor/symfony/dependency-injection/ContainerBuilder.php(897): Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices(Array)
#8 .../vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'http_client_fac...')
#9 .../vendor/symfony/dependency-injection/ContainerBuilder.php(985): Symfony\Component\DependencyInjection\ContainerBuilder->get('http_client_fac...', 1)
#10 .../vendor/symfony/dependency-injection/ContainerBuilder.php(901): Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices(Object(Symfony\Component\DependencyInjection\Reference))
#11 .../vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'http_client')
#12 .../vendor/symfony/dependency-injection/ContainerBuilder.php(985): Symfony\Component\DependencyInjection\ContainerBuilder->get('http_client', 1)
#13 .../vendor/symfony/dependency-injection/ContainerBuilder.php(982): Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices(Object(Symfony\Component\DependencyInjection\Reference))
#14 .../vendor/symfony/dependency-injection/ContainerBuilder.php(897): Symfony\Component\DependencyInjection\ContainerBuilder->resolveServices(Array)
#15 .../vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.extensi...')
#16 .../vendor/drupal/console/src/Bootstrap/AddServicesCompilerPass.php(72): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.extensi...')
#17 .../vendor/symfony/dependency-injection/Compiler/Compiler.php(104): Drupal\Console\Bootstrap\AddServicesCompilerPass->process(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#18 .../vendor/symfony/dependency-injection/ContainerBuilder.php(590): Symfony\Component\DependencyInjection\Compiler\Compiler->compile(Object(Drupal\Core\DependencyInjection\ContainerBuilder))
#19 .../web/core/lib/Drupal/Core/DrupalKernel.php(1254): Symfony\Component\DependencyInjection\ContainerBuilder->compile()
#20 .../web/core/lib/Drupal/Core/DrupalKernel.php(866): Drupal\Core\DrupalKernel->compileContainer()
#21 .../web/core/lib/Drupal/Core/DrupalKernel.php(1114): Drupal\Core\DrupalKernel->initializeContainer()
#22 .../vendor/drupal/console/src/Bootstrap/Drupal.php(103): Drupal\Core\DrupalKernel->rebuildContainer()
#23 .../vendor/drupal/console/bin/drupal.php(49): Drupal\Console\Bootstrap\Drupal->boot(false)
#24 .../vendor/drupal/console/bin/drupal(4): require('/home/ao2/publi...')
#25 {main}
TypeError: Argument 2 passed to Drupal\Core\Http\HandlerStackConfigurator::__construct() must be of the type array, none given in Drupal\Core\Http\HandlerStackConfigurator->__construct() (line 53 of .../web/core/lib/Drupal/Core/Http/HandlerStackConfigurator.php).
```

Any idea of what is going on?

Thanks,
   Antonio

**Comment by ao2** [comment]
@jmolivas, ping. Any chance you can give an advice?

Thanks,
   Antonio

**Comment by jmolivas** [comment]
@ao2 are you on the gitter channel https://gitter.im/hechoendrupal/DrupalConsole ?

**Comment by ao2** [comment]
@jmolivas I am not and I don't plan to be, but I am on IRC on Freenode.net, where the official Drupal channels are.

**Comment by ao2** [comment]
Following the message trace from above, the issue with `@http_client` seems to be about this snippet in Drupal `core/core.services.yml`:

```
...
http_handler_stack_configurator:
    class: Drupal\Core\Http\HandlerStackConfigurator
    public: false
    arguments: ['@service_container']
...
```

here only one argument is passed, while in `core/lib/Drupal/Core/Http/HandlerStackConfigurator.php` the constructor actually expects two arguments:
```
public function __construct(ContainerInterface $container, array $middleware_ids) {
...
```

The following patch to Drupal core fixes the problem shown in one of my previous comments:
```
diff --git a/core/lib/Drupal/Core/Http/HandlerStackConfigurator.php b/core/lib/Drupal/Core/Http/HandlerStackConfigurator.php
index 69e3913084..59c71d77d0 100644
--- a/core/lib/Drupal/Core/Http/HandlerStackConfigurator.php
+++ b/core/lib/Drupal/Core/Http/HandlerStackConfigurator.php
@@ -33,7 +33,7 @@ class HandlerStackConfigurator {
    *
    * @var string[]
    */
-  protected $middlewareIds = [];
+  protected $middlewareIds;

   /**
    * The service container.
@@ -50,7 +50,7 @@ class HandlerStackConfigurator {
    * @param string[] $middleware_ids
    *   The middleware IDs.
    */
-  public function __construct(ContainerInterface $container, array $middleware_ids) {
+  public function __construct(ContainerInterface $container, array $middleware_ids = []) {
     $this->middlewareIds = $middleware_ids;
     $this->container = $container;
   }
```

@jmolivas does this explanation make sense to you? Should I file an issue for Drupal core or can console do something about it?

Just to recap, the issue showed up when I tried to use `http_client` as an argument to console's `extension_manager`, and after the patch above this works just fine and I can get on with the refactoring of `checkDependencies` into `checkExtensions`.

I can also show you the full refactoring if this helps you to put this particular issue with `http_client` and `extension_manager` in context.

Thanks,
   Antonio

**Comment by ao2** [comment]
After further analysis, it looks that trying to use `http_client` **too early** creates problems because the core service container is not fully initialized, for instance the missing argument in Drupal `core.services.yml` I was referring to in the previous comment is actually added by Drupal in `core/lib/Drupal/Core/DependencyInjection/Compiler/GuzzleMiddlewarePass.php`, called by `CoreServiceProvider`, called in `DrupalKernel::initializeServiceProviders`.  

My current hypothesis is that when I try to instantiate `ExtensionManager` with the `@http_client` argument the core services have not been fully initialized yet, so they are created *on demand* (see the backtrace I posted before) but the missing argument does not get added because `GuzzleMiddlewarePass` is not called. 

However I am too new to this services thing, I still don't understand why using `http_client` as an argument to a command is fine, but using it in `extension_manager` gives problem , so I am back at asking for help :)

Thanks,
   Antonio

**Comment by ao2** [comment]
@jmolivas the recent work about consolidating the compilation of services files (in particular #3155) seems to have fixed the problem I was having about using the `http_client` service in `ExtensionManager`.

I'll take a better look in the next days and hopefully I'll be able to send a pull request to close this issue.

Thanks,
   Antonio

**Comment by jmolivas** [comment]
@ao2 Glad to read that, I will tag a new release soon, ping you once is tagged so you can test and close issue if fixed.
