### ISSUE TITLE
config:export:single: Error: Call to a member function getModule() on null

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3305]
Not sure if this is project specific, but I'm currently getting the following error on `drupal config:export:single` with RC17:

```
Error: Call to a member function getModule() on null in /path/to/project/vendor/drupal/console/src/Command/Shared/ExportTrait.php on line 81 #0 /path/to/project/vendor/drupal/console/src/Command/Config/ExportSingleCommand.php(270): Drupal\Console\Command\Config\ExportSingleCommand->exportConfigToModule('fish_recipes', Object(Drupal\Console\Core\Style\DrupalStyle), 'Configuration(s...')
#1 /path/to/project/vendor/symfony/console/Command/Command.php(264): Drupal\Console\Command\Config\ExportSingleCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /path/to/project/vendor/symfony/console/Application.php(868): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /path/to/project/vendor/symfony/console/Application.php(192): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Config\ExportSingleCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /path/to/project/vendor/drupal/console-core/src/Application.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /path/to/project/vendor/drupal/console/src/Application.php(49): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /path/to/project/vendor/symfony/console/Application.php(123): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /path/to/project/vendor/drupal/console/bin/drupal.php(68): Symfony\Component\Console\Application->run()
#8 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('...')
#9 phar:///usr/local/bin/drupal/bin/drupal.php(55): Drupal\Console\Launcher\Utils\Launcher->launch('...')
#10 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#11 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#12 {main}
Error: Call to a member function getModule() on null in Drupal\Console\Command\Config\ExportSingleCommand->exportConfigToModule() (line 81 of /path/to/project/vendor/drupal/console/src/Command/Shared/ExportTrait.php).
```

**Edit**: Just checked, this problem also exists with RC19:
```
$ drupal --version
Drupal Console Launcher version 1.0.0-rc19
Drupal Console version 1.0.0-rc19
```

**Edit 2**: For reproducibility, see following command with inline parameters and flags. Note that image.style.compact is simply a example, all configs fail. Also, it states that export was successful, but I do not see any exported files. 

```
$ drupal config:export:single --name=image.style.compact --module=MODULE_NAME --include-dependencies --remove-uuid --remove-config-hash --optional
 Configuration(s) exported sucessfully


  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Call to a member function getModule() on null
```

**Comment by nvaken** [comment]
Above pull request fixes this issue.
