### ISSUE TITLE
[console] console launcher rc21 fatal error

### ISSUE THREAD

**Issue by LatinRickshaw** [hechoendrupal/drupal-console#3352]
### [console] console launcher rc21 fatal error

Since we have updated Drupal we can no longer run Drupal Console commands without a Fatal Error.

### Problem
The problem is a PHP Fatal Error notice when running Drupal Console: -

```
#drupal
                                                                                                                                                           
Recoverable fatal error: Argument 5 passed to Drupal\Console\Command\Generate\CommandCommand::__construct() must be an instance of Drupal\Console\Utils\Site, none given in ///vendor/drupal/console/src/Command/Generate/CommandCommand.php on line 74 #0 ///web/core/includes/bootstrap.inc(552): _drupal_error_handler_real(4096, 'Argument 5 pass...', '/var/www/sites_...', 74, Array)     
#1 ///vendor/drupal/console/src/Command/Generate/CommandCommand.php(74): _drupal_error_handler(4096, 'Argument 5 pass...', '/var/www/sites_...', 74, Array)                                     
#2 [internal function]: Drupal\Console\Command\Generate\CommandCommand->__construct(Object(Drupal\Console\Generator\CommandGenerator), Object(Drupal\Console\Extension\Manager), Object(Drupal\Console\Utils\Validator), Object(Drupal\Console\Core\Utils\StringConverter))                                                                                                                                                                                     
#3 ///vendor/symfony/dependency-injection/ContainerBuilder.php(936): ReflectionClass->newInstanceArgs(Array)                                                                                    
#4 ///vendor/symfony/dependency-injection/ContainerBuilder.php(476): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.generat...')                                                                                                                                                                                                      
#5 ///vendor/drupal/console/src/Application.php(192): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.generat...')                                                         
#6 ///vendor/drupal/console/src/Application.php(63): Drupal\Console\Application->registerCommands()                                                                                             
#7 ///vendor/symfony/console/Application.php(127): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) 
#8 ///vendor/drupal/console/bin/drupal.php(66): Symfony\Component\Console\Application->run()                                                                                                    
#9 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('/var/www/sites_...')                                                                                                                                  
#10 phar:///usr/local/bin/drupal/bin/drupal.php(71): Drupal\Console\Launcher\Utils\Launcher->launch(Object(DrupalFinder\DrupalFinder))                                                                                          
#11 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')                                                                                                                                                   
#12 /usr/local/bin/drupal(10): require('phar:///usr/loc...')                                                                                                                                                                    
#13 {main}   
                                                                                                                                                        
Recoverable fatal error: Argument 5 passed to Drupal\Console\Command\Generate\CommandCommand::__construct() must be an instance of Drupal\Console\Utils\Site, none given in Drupal\Console\Command\Generate\CommandCommand->__construct() (line 74 of ///vendor/drupal/console/src/Command/Generate/CommandCommand.php).
```

Coming from Symfony I am an advocate for Drupal Console and would love to see it working again.

### How to reproduce
Drupal Version: 8.3.1
Console Version: -
drupal/console                        1.0.0-rc21         The Drupal CLI. A tool to generate boilerplate code, interact with and debug Drupal.                                                                                   
drupal/console-core                   1.0.0-rc21         Drupal Console Core                                                                                                                                                    
drupal/console-en                     1.0.0-rc21         Drupal Console English Language                                                                                                                                        
drupal/console-extend-plugin          0.8.0              Drupal Console Extend Plugin
Console Launcher Version: 1.0.0-rc21

To reproduce run 'drupal' from the command line within the root of the Drupal 8 project.

**Comment by jmolivas** [comment]
@LatinRickshaw  Try rebuilding cache `drupal cr all`

**Comment by cburschka-pwc** [comment]
You can't run `drupal cr all` if DC can't even bootstrap due to bad service definitions. ;-)

I solved a similar issue in #3354 by deleting `./.console` and `~/.console/` and truncating all of the `cache_` tables in the database manually. (Only a subset of these might have been required.)

**Comment by LatinRickshaw** [comment]
@cburschka-pwc Absolutely spot on. Deleting my home directory .console folder and manually clearing the cache tables has brought drupal console back to life.

Thank you...

**Comment by msypes** [comment]
Thanks @cburschka-pwc 
I was having similar issues (https://github.com/hechoendrupal/drupal-console/issues/3281#issuecomment-317853240) and your advice to delete `~/.console` really cleared it
