### ISSUE TITLE
Argument 3 passed to Drupal\Console\Command\Config\ExportSingleCommand::__construct() must be an instance of Drupal\Console\Extension\Manager, none given

### ISSUE THREAD

**Issue by welly** [hechoendrupal/drupal-console#3414]
Just tried to run drupal router:rebuild and actually any console command and get the following errors:

```
TypeError: Argument 3 passed to Drupal\Console\Command\Config\ExportSingleCommand::__construct() must be an instance of Drupal\Console\Extension\Manager, none given in /server/www/example/dev/vendor/drupal/console/src/Command/Config/ExportSingleCommand.php on line 52 #0 [internal function]: Drupal\Console\Command\Config\ExportSingleCommand->__construct(Object(Drupal\webprofiler\Entity\EntityManagerWrapper), Object(Drupal\fb_config_readonly\Config\FbConfigReadonlyStorage))
#1 /server/www/example/dev/vendor/symfony/dependency-injection/ContainerBuilder.php(936): ReflectionClass->newInstanceArgs(Array)
#2 /server/www/example/dev/vendor/symfony/dependency-injection/ContainerBuilder.php(476): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.config_...')
#3 /server/www/example/dev/vendor/drupal/console/src/Application.php(192): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.config_...')
#4 /server/www/example/dev/vendor/drupal/console/src/Application.php(63): Drupal\Console\Application->registerCommands()
#5 /server/www/example/dev/vendor/symfony/console/Application.php(127): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /server/www/example/dev/vendor/drupal/console/bin/drupal.php(84): Symfony\Component\Console\Application->run()
#7 /server/www/example/dev/vendor/drupal/console/bin/drupal(4): require('/server/www/exam...')
#8 {main}
TypeError: Argument 3 passed to Drupal\Console\Command\Config\ExportSingleCommand::__construct() must be an instance of Drupal\Console\Extension\Manager, none given in Drupal\Console\Command\Config\ExportSingleCommand->__construct() (line 52 of /server/www/example/dev/vendor/drupal/console/src/Command/Config/ExportSingleCommand.php).
```

I've tried deleting the vendor/drupal/console directory and running composer install and also running composer update drupal/console which both completed (although update didn't update anything) but no luck in resolving the issue.

console version is:

>             "name": "drupal/console",
>             "version": "1.0.0-rc23",
>             "source": {
>                 "type": "git",
>                 "url": "https://github.com/hechoendrupal/drupal-console.git",
>                 "reference": "2bac21223573f5fd8c4d7b725baf5d404e406b0b"
>             },

Cheers

**Comment by jmolivas** [comment]
@welly try rebuilding DrupalConsole caches executing `drupal cr all`

**Comment by welly** [comment]
@jmolivas alas no luck, running `drupal cr all` results in the following error:

```
TypeError: Argument 1 passed to Drupal\Console\Command\Breakpoints\DebugCommand::__construct() must be an instance of Drupal\breakpoint\BreakpointManagerInterface, none given in /server/www/nuffield/dev/vendor/drupal/console/src/Command/Breakpoints/DebugCommand.php on line 46 #0 [internal function]: Drupal\Console\Command\Breakpoints\DebugCommand->__construct()
#1 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(927): ReflectionClass->newInstanceArgs(Array)
#2 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(475): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'breakpoints_deb...')
#3 phar:///usr/local/bin/drupal/src/Helper/ContainerHelper.php(40): Symfony\Component\DependencyInjection\ContainerBuilder->get('breakpoints_deb...')
#4 phar:///usr/local/bin/drupal/src/Application.php(374): Drupal\Console\Helper\ContainerHelper->get('breakpoints_deb...')
#5 phar:///usr/local/bin/drupal/src/Application.php(322): Drupal\Console\Application->registerCommands(Array)
#6 phar:///usr/local/bin/drupal/src/Application.php(245): Drupal\Console\Application->prepare(Object(Drupal\Console\Helper\DrupalHelper), 'cr')
#7 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(123): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Drupal\Console\Style\DrupalStyle))
#8 phar:///usr/local/bin/drupal/bin/drupal.php(115): Symfony\Component\Console\Application->run()
#9 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#10 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#11 {main}
TypeError: Argument 1 passed to Drupal\Console\Command\Breakpoints\DebugCommand::__construct() must be an instance of Drupal\breakpoint\BreakpointManagerInterface, none given in Drupal\Console\Command\Breakpoints\DebugCommand->__construct() (line 46 of /server/www/nuffield/dev/vendor/drupal/console/src/Command/Breakpoints/DebugCommand.php).
```

I've manually deleted the .console directory and tried running console commands again but no luck still.

Seems strange as I've had this working fine before and I'm not aware of any updates.

The only thing I can think of is this is a system wide install of drupal console and I have a local install of console in my project but the path isn't set for that so have to run ./vendor/drupal/console/bin/console if I want to run that one. That version triggers a different error though:

```
[ERROR] You have requested a non-existent service "console.configuration_manager".

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "console.configuration_manager". in /server/www/nuffield/dev/vendor/symfony/dependency-injection/ContainerBuilder.php on line 824 #0 /server/www/nuffield/dev/vendor/symfony/dependency-injection/ContainerBuilder.php(464): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('console.configu...')
#1 /server/www/nuffield/dev/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(64): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.configu...')
#2 /server/www/nuffield/dev/vendor/drupal/console/src/Bootstrap/Drupal.php(175): Drupal\Console\Core\Bootstrap\DrupalConsoleCore->boot()
#3 /server/www/nuffield/dev/vendor/drupal/console/bin/drupal.php(74): Drupal\Console\Bootstrap\Drupal->boot()
#4 /server/www/nuffield/dev/vendor/drupal/console/bin/drupal(4): require('/server/www/nuf...')
#5 {main}
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "console.configuration_manager". in Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() (line 824 of /server/www/nuffield/dev/vendor/symfony/dependency-injection/ContainerBuilder.php).
```

**Comment by jmolivas** [comment]
@welly  Can you check if you have a `console/cache` directory at your site root path or an empty `composer.json` at `web` or `docroot` directory?

**Comment by jmolivas** [comment]
@welly try `cd path/to/drupal` and execute:

```
composer install
drupal cr all
```

**Comment by welly** [comment]
Well, something seems to have fixed itself. I deleted the cache directory and had actually deployed some new code and it all seems to be working again, at least the local project version as opposed to the system wide version (that still doesn't work! But that's fine). I'm not entirely sure what resolved it but seems to be ok. Version is 1.0.0-rc25 on the project version. I'll close this. Thank you!
