### ISSUE TITLE
Drupal\Core\Installer\Exception\InstallerException: PHP extensions: Disabled Array

### ISSUE THREAD

**Issue by nvaken** [hechoendrupal/drupal-console#3528]
When using drupal console to install a standard install on a server which misses some extensions I get an "Array" as error message:

```
$ ../vendor/bin/drupal site:install

 Select Drupal profile to be installed:
  [0] minimal
  [1] standard
  [2] tienuur_default
 > 1

 Select language for your Drupal installation [English]:
 >
 Using "mysql" database with name "project" and user "root"

 Provide your Drupal site name [My awesome site]:
 >

 Provide your Drupal site mail [admin@example.com]:
 >

 Provide your Drupal administrator account name [admin]:
 >

 Provide your Drupal administrator account password:
 >

 Provide your Drupal administrator account mail [admin@example.com]:
 >


 Starting Drupal 8 install process



 [ERROR] PHP extensions: Disabled

         Array

```

Not entirely sure if this is related to DC, since Drush seems to return an "Array" as well:

```
# ../vendor/bin/drush si
You are about to DROP all tables in your 'project' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option.                                                                            [ok]
Drupal\Core\Installer\Exception\InstallerException: PHP extensions: Disabled                                                                                            [error]

Array in /var/www/drupal_app/releases/32/web/core/includes/install.core.inc:2185
Stack trace:
#0 /var/www/drupal_app/releases/32/web/core/includes/install.core.inc(1028): install_display_requirements(Array, Array)
#1 /var/www/drupal_app/releases/32/web/core/includes/install.core.inc(662): install_verify_requirements(Array)
#2 /var/www/drupal_app/releases/32/web/core/includes/install.core.inc(540): install_run_task(Array, Array)
#3 /var/www/drupal_app/releases/32/web/core/includes/install.core.inc(117): install_run_tasks(Array)
#4 /var/www/drupal_app/releases/32/vendor/drush/drush/includes/drush.inc(726): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#5 /var/www/drupal_app/releases/32/vendor/drush/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)
#6 /var/www/drupal_app/releases/32/vendor/drush/drush/commands/core/drupal/site_install.inc(82): drush_op('install_drupal', Object(Composer\Autoload\ClassLoader),
Array)
#7 /var/www/drupal_app/releases/32/vendor/drush/drush/commands/core/site_install.drush.inc(255): drush_core_site_install_version('standard', Array)
#8 /var/www/drupal_app/releases/32/vendor/drush/drush/includes/command.inc(422): drush_core_site_install()
#9 /var/www/drupal_app/releases/32/vendor/drush/drush/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#10 /var/www/drupal_app/releases/32/vendor/drush/drush/includes/command.inc(199): drush_command()
#11 /var/www/drupal_app/releases/32/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#12 /var/www/drupal_app/releases/32/vendor/drush/drush/includes/preflight.inc(66): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#13 /var/www/drupal_app/releases/32/vendor/drush/drush/drush.php(12): drush_main()
#14 {main}
```

Drupal Console version 1.0.0-rc26

**Comment by nvaken** [comment]
Might be a dupe of:
https://www.drupal.org/node/2833864

**Comment by nvaken** [comment]
I'll close this one, seems like this issue in Core as shown in above issue. 

Checking which extensions should be enabled is of course easily done by using the web interface of the installer. 
![image](https://user-images.githubusercontent.com/503360/30694988-ab4f0dd0-9ed6-11e7-94d8-c2aed1675098.png)
