### ISSUE TITLE
DrupalConsole should guess HOME environment variable

### ISSUE THREAD

**Issue by novia713** [hechoendrupal/drupal-console#3612]
### DrupalConsole should guess HOME environment variable

This is the error it throws when it can't find HOME environment variable
```
  root@ns3010321.ip-94-23-248.eu   master U:1  ~/root/html/api_nexum  drupal cr all
PHP Fatal error:  Uncaught RuntimeException: Your environment or operation system isn't supported in phar:///usr/local/bin/drupal/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Utils/ConfigurationManager.php(48): Webmozart\PathUtil\Path::getHomeDirectory()
#1 phar:///usr/local/bin/drupal/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(65): Drupal\Console\Core\Utils\ConfigurationManager->loadConfiguration('phar:///usr/loc...')
#2 phar:///usr/local/bin/drupal/bin/drupal.php(40): Drupal\Console\Core\Bootstrap\DrupalConsoleCore->boot()
#3 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#4 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#5 {main}
  thrown in phar:///usr/local/bin/drupal/vendor/webmozart/path-util/src/Path.php on line 257
```

@jmolivas can you suggest a library to handle this?
i would like to solve this problem.

**Comment by jmolivas** [comment]
@novia713 This issue should be fixed at the https://github.com/hechoendrupal/drupal-console-core repository 

We are already using the https://github.com/webmozart/path-util package we can use it as:
```
use Webmozart\PathUtil\Path;

Path::getHomeDirectory();
```

**Comment by novia713** [comment]
opened https://github.com/hechoendrupal/drupal-console-core/issues/255
i close this issue
