### ISSUE TITLE
[generate:entity:content] Content entities throw fatal errors when installed

### ISSUE THREAD

**Issue by mikestefanello** [hechoendrupal/drupal-console#3766]
**Drupal 8.4.4
Drupal console: 1.5.0**

Created a content entity. When trying to install the module that contains the entity type, I receive these errors:

```
PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064[error]
You have an error in your SQL syntax; check the manual that
corresponds to your MySQL server version for the right syntax to use
near 'position (
`id` INT unsigned NOT NULL auto_increment, 
`uuid` VARCHAR(128) CHARA' at line 1 in
/var/www/docroot/core/lib/Drupal/Core/Database/Statement.php:59
Stack trace:
#0 /var/www/docroot/core/lib/Drupal/Core/Database/Statement.php(59):
PDOStatement->execute(Array)
#1
/var/www/docroot/core/lib/Drupal/Core/Database/Connection.php(625):
Drupal\Core\Database\Statement->execute(Array, Array)
#2
/var/www/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87):
Drupal\Core\Database\Connection->query('CREATE TABLE {p...', Array,
Array)
#3 /var/www/docroot/core/lib/Drupal/Core/Database/Schema.php(602):
Drupal\Core\Database\Driver\mysql\Connection->query('CREATE TABLE
{p...')
#4
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorageSchema.php(288):
Drupal\Core\Database\Schema->createTable('position', Array)
#5
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1409):
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#6
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1505):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->Drupal\Core\Entity\Sql\{closure}()
#7
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1410):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object(Closure))
#8
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityTypeListener.php(71):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#9
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityManager.php(534):
Drupal\Core\Entity\EntityTypeListener->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#10
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php(135):
Drupal\Core\Entity\EntityManager->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#11
/var/www/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(234):
Drupal\Core\Entity\EntityDefinitionUpdateManager->installEntityType(Object(Drupal\Core\Entity\ContentEntityType))
#12
/var/www/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#13 /var/www/docroot/core/includes/install.core.inc(1805):
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array,
false)
#14 /var/www/docroot/core/includes/batch.inc(294):
_install_module_batch('my_module', 'my_module', Array)
#15 /var/www/docroot/core/includes/form.inc(875): _batch_process()
#16 /var/www/docroot/core/includes/install.core.inc(628):
batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#17 /var/www/docroot/core/includes/install.core.inc(549):
install_run_task(Array, Array)
#18 /var/www/docroot/core/includes/install.core.inc(117):
install_run_tasks(Array)
#19 phar:///usr/local/bin/drush/includes/drush.inc(726):
install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#20 phar:///usr/local/bin/drush/includes/drush.inc(711):
drush_call_user_func_array('install_drupal', Array)
#21
phar:///usr/local/bin/drush/commands/core/drupal/site_install.inc(82):
drush_op('install_drupal', Object(Composer\Autoload\ClassLoader),
Array)
#22
phar:///usr/local/bin/drush/commands/core/site_install.drush.inc(255):
drush_core_site_install_version('my_install_profile', Array)
#23 phar:///usr/local/bin/drush/includes/command.inc(422):
drush_core_site_install('my_install_profile')
#24 phar:///usr/local/bin/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#25 phar:///usr/local/bin/drush/includes/command.inc(199):
drush_command('my_install_profile')
#26 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#27 phar:///usr/local/bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#28 phar:///usr/local/bin/drush/includes/startup.inc(458):
drush_main()
#29 phar:///usr/local/bin/drush/includes/startup.inc(365):
drush_run_main(false, '/', 'Phar detected. ...')
#30 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#31 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#32 {main}

Next Drupal\Core\Database\DatabaseExceptionWrapper: SQLSTATE[42000]:
Syntax error or access violation: 1064 You have an error in your SQL
syntax; check the manual that corresponds to your MySQL server
version for the right syntax to use near 'position (
`id` INT unsigned NOT NULL auto_increment, 
`uuid` VARCHAR(128) CHARA' at line 1: CREATE TABLE {position} (
`id` INT unsigned NOT NULL auto_increment, 
`uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT
NULL, 
`langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci
NOT NULL, 
`user_id` INT unsigned NOT NULL COMMENT 'The ID of the target
entity.', 
`name` VARCHAR(50) NULL DEFAULT NULL, 
`status` TINYINT NOT NULL, 
`created` INT NULL DEFAULT NULL, 
`changed` INT NULL DEFAULT NULL, 
PRIMARY KEY (`id`), 
UNIQUE KEY `position_field__uuid__value` (`uuid`), 
INDEX `position_field__user_id__target_id` (`user_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base
table for position entities.'; Array
(
)
 in /var/www/docroot/core/lib/Drupal/Core/Database/Connection.php:686
Stack trace:
#0
/var/www/docroot/core/lib/Drupal/Core/Database/Connection.php(650):
Drupal\Core\Database\Connection->handleQueryException(Object(PDOException),
'CREATE TABLE {p...', Array, Array)
#1
/var/www/docroot/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(87):
Drupal\Core\Database\Connection->query('CREATE TABLE {p...', Array,
Array)
#2 /var/www/docroot/core/lib/Drupal/Core/Database/Schema.php(602):
Drupal\Core\Database\Driver\mysql\Connection->query('CREATE TABLE
{p...')
#3
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorageSchema.php(288):
Drupal\Core\Database\Schema->createTable('position', Array)
#4
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1409):
Drupal\Core\Entity\Sql\SqlContentEntityStorageSchema->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#5
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1505):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->Drupal\Core\Entity\Sql\{closure}()
#6
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1410):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object(Closure))
#7
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityTypeListener.php(71):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#8
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityManager.php(534):
Drupal\Core\Entity\EntityTypeListener->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#9
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php(135):
Drupal\Core\Entity\EntityManager->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#10
/var/www/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(234):
Drupal\Core\Entity\EntityDefinitionUpdateManager->installEntityType(Object(Drupal\Core\Entity\ContentEntityType))
#11
/var/www/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#12 /var/www/docroot/core/includes/install.core.inc(1805):
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array,
false)
#13 /var/www/docroot/core/includes/batch.inc(294):
_install_module_batch('my_module', 'my_module', Array)
#14 /var/www/docroot/core/includes/form.inc(875): _batch_process()
#15 /var/www/docroot/core/includes/install.core.inc(628):
batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#16 /var/www/docroot/core/includes/install.core.inc(549):
install_run_task(Array, Array)
#17 /var/www/docroot/core/includes/install.core.inc(117):
install_run_tasks(Array)
#18 phar:///usr/local/bin/drush/includes/drush.inc(726):
install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#19 phar:///usr/local/bin/drush/includes/drush.inc(711):
drush_call_user_func_array('install_drupal', Array)
#20
phar:///usr/local/bin/drush/commands/core/drupal/site_install.inc(82):
drush_op('install_drupal', Object(Composer\Autoload\ClassLoader),
Array)
#21
phar:///usr/local/bin/drush/commands/core/site_install.drush.inc(255):
drush_core_site_install_version('my_install_profile', Array)
#22 phar:///usr/local/bin/drush/includes/command.inc(422):
drush_core_site_install('my_install_profile')
#23 phar:///usr/local/bin/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#24 phar:///usr/local/bin/drush/includes/command.inc(199):
drush_command('my_install_profile')
#25 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#26 phar:///usr/local/bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#27 phar:///usr/local/bin/drush/includes/startup.inc(458):
drush_main()
#28 phar:///usr/local/bin/drush/includes/startup.inc(365):
drush_run_main(false, '/', 'Phar detected. ...')
#29 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#30 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#31 {main}

Next Drupal\Core\Entity\EntityStorageException: Exception thrown
while performing a schema update. SQLSTATE[42000]: Syntax error or
access violation: 1064 You have an error in your SQL syntax; check
the manual that corresponds to your MySQL server version for the
right syntax to use near 'position (
`id` INT unsigned NOT NULL auto_increment, 
`uuid` VARCHAR(128) CHARA' at line 1: CREATE TABLE {position} (
`id` INT unsigned NOT NULL auto_increment, 
`uuid` VARCHAR(128) CHARACTER SET ascii COLLATE ascii_general_ci NOT
NULL, 
`langcode` VARCHAR(12) CHARACTER SET ascii COLLATE ascii_general_ci
NOT NULL, 
`user_id` INT unsigned NOT NULL COMMENT 'The ID of the target
entity.', 
`name` VARCHAR(50) NULL DEFAULT NULL, 
`status` TINYINT NOT NULL, 
`created` INT NULL DEFAULT NULL, 
`changed` INT NULL DEFAULT NULL, 
PRIMARY KEY (`id`), 
UNIQUE KEY `position_field__uuid__value` (`uuid`), 
INDEX `position_field__user_id__target_id` (`user_id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET utf8mb4 COMMENT 'The base
table for position entities.'; Array
(
)
 in
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php:1513
Stack trace:
#0
/var/www/docroot/core/lib/Drupal/Core/Entity/Sql/SqlContentEntityStorage.php(1410):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->wrapSchemaException(Object(Closure))
#1
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityTypeListener.php(71):
Drupal\Core\Entity\Sql\SqlContentEntityStorage->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#2
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityManager.php(534):
Drupal\Core\Entity\EntityTypeListener->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#3
/var/www/docroot/core/lib/Drupal/Core/Entity/EntityDefinitionUpdateManager.php(135):
Drupal\Core\Entity\EntityManager->onEntityTypeCreate(Object(Drupal\Core\Entity\ContentEntityType))
#4
/var/www/docroot/core/lib/Drupal/Core/Extension/ModuleInstaller.php(234):
Drupal\Core\Entity\EntityDefinitionUpdateManager->installEntityType(Object(Drupal\Core\Entity\ContentEntityType))
#5
/var/www/docroot/core/lib/Drupal/Core/ProxyClass/Extension/ModuleInstaller.php(83):
Drupal\Core\Extension\ModuleInstaller->install(Array, false)
#6 /var/www/docroot/core/includes/install.core.inc(1805):
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array,
false)
#7 /var/www/docroot/core/includes/batch.inc(294):
_install_module_batch('my_module', 'my_module', Array)
#8 /var/www/docroot/core/includes/form.inc(875): _batch_process()
#9 /var/www/docroot/core/includes/install.core.inc(628):
batch_process(Object(Drupal\Core\Url), Object(Drupal\Core\Url))
#10 /var/www/docroot/core/includes/install.core.inc(549):
install_run_task(Array, Array)
#11 /var/www/docroot/core/includes/install.core.inc(117):
install_run_tasks(Array)
#12 phar:///usr/local/bin/drush/includes/drush.inc(726):
install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#13 phar:///usr/local/bin/drush/includes/drush.inc(711):
drush_call_user_func_array('install_drupal', Array)
#14
phar:///usr/local/bin/drush/commands/core/drupal/site_install.inc(82):
drush_op('install_drupal', Object(Composer\Autoload\ClassLoader),
Array)
#15
phar:///usr/local/bin/drush/commands/core/site_install.drush.inc(255):
drush_core_site_install_version('my_install_profile', Array)
#16 phar:///usr/local/bin/drush/includes/command.inc(422):
drush_core_site_install('my_install_profile')
#17 phar:///usr/local/bin/drush/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#18 phar:///usr/local/bin/drush/includes/command.inc(199):
drush_command('my_install_profile')
#19 phar:///usr/local/bin/drush/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#20 phar:///usr/local/bin/drush/includes/preflight.inc(66):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#21 phar:///usr/local/bin/drush/includes/startup.inc(458):
drush_main()
#22 phar:///usr/local/bin/drush/includes/startup.inc(365):
drush_run_main(false, '/', 'Phar detected. ...')
#23 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#24 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#25 {main}


```

**Comment by mikestefanello** [comment]
Turns out the name "position" cannot be used for a database table.
