### ISSUE TITLE
lightning:subprofile command bails with traits error

### ISSUE THREAD

**Issue by rsaddington** [hechoendrupal/drupal-console#3812]
When using console to create a subprofile of the lightning distribution I'm seeing an error in the way traits are handled.

Not sure if this is a bug in console or in the lightning implementation of console commands.

Run drupal lightning:subprofile with the following setup:
BLT 8.9.12
PHP 7.1
Drupal 8.4.5
Lightning 3.0.2
Console 1.6.1

Here's the error:
Error: Call to undefined method Drupal\lightning\Command\SubProfileCommand::getIo() in /var/www/blt-sf/vendor/drupal/console/src/Command/Shared/ConfirmationTrait.php on line 23 #0 /var/www/blt-sf/vendor/drupal/console/src/Command/Shared/ConfirmationTrait.php(46): Drupal\lightning\Command\SubProfileCommand->confirmOperation()
#1 /var/www/blt-sf/docroot/profiles/contrib/lightning/src/Command/SubProfileCommand.php(409): Drupal\lightning\Command\SubProfileCommand->confirmGeneration(Object(Drupal\Console\Core\Style\DrupalStyle))
#2 /var/www/blt-sf/vendor/symfony/console/Command/Command.php(264): Drupal\lightning\Command\SubProfileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /var/www/blt-sf/vendor/symfony/console/Application.php(859): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 /var/www/blt-sf/vendor/symfony/console/Application.php(206): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\lightning\Command\SubProfileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/www/blt-sf/vendor/drupal/console-core/src/Application.php(185): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/blt-sf/vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/blt-sf/vendor/symfony/console/Application.php(125): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/blt-sf/vendor/drupal/console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#9 /var/www/blt-sf/vendor/drupal/console/bin/drupal(4): require('/var/www/blt-sf...')
#10 {main}
Error: Call to undefined method Drupal\lightning\Command\SubProfileCommand::getIo() in Drupal\lightning\Command\SubProfileCommand->confirmOperation() (line 23 of /var/www/blt-sf/vendor/drupal/console/src/Command/Shared/ConfirmationTrait.php).

**Comment by LOBsTerr** [comment]
@rsaddington I'm not sure, but it looks like that Drupal Console core is old one you are missing this code:
https://github.com/hechoendrupal/drupal-console-core/blob/e05f954412da7c2a496fd1c92f4cfe63debe43ed/src/Command/Command.php#L41

Can you check that core is also up to date ?

**Comment by dlopez-akalam** [comment]
I think is the same issue here https://www.drupal.org/project/lightning/issues/2955286#comment-12539534
