### ISSUE TITLE
[site:install] Fails for custom profile with Bootstrap subtheme

### ISSUE THREAD

**Issue by zenlan** [hechoendrupal/drupal-console#3879]
### Problem/Motivation
My custom profile is consistently successful when installed via the Drupal UI but fails with a fatal error using the console [site:install] command.

### How to reproduce

- Drupal version 8.5.3
- Console version 1.8.0
- Console Launcher version 1.8.0

1. Create a Bootstrap subtheme

2. Create a custom profile based on the standard Drupal profile, include the subtheme
```
...
themes:
  - 'bartik'
  - 'seven'
  - 'mybootstrap_subtheme'
```
3. Execute the site:install command with the custom profile argument
```
$ /var/www/html/mysite.dev/web $ drupal site:install mysite_profile  \
> --langcode="en"  \
> --db-type="mysql"  \
> --db-host="127.0.0.1"  \
> --db-name="drupal8"  \
> --db-user="drupal8"  \
> --db-pass="drupal8"  \
> --db-port="3306"  \
> --site-name="My Site"  \
> --site-mail="admin@example.com"  \
> --account-name="admin"  \
> --account-mail="admin@example.com"  \
> --account-pass="admin"

 Database Prefix []:
 >

Starting Drupal 8 install process
Error: Class 'Drupal\bootstrap\Bootstrap' not found in /var/www/html/mysite.dev/web/themes/contrib/bootstrap/bootstrap.theme on line 31 #0 /var/www/html/mysite.dev/web/core/lib/Drupal/Core/Extension/Extension.php(140): include_once()
#1 /var/www/html/mysite.dev/web/core/themes/engines/twig/twig.engine(35): Drupal\Core\Extension\Extension->load()
#2 [internal function]: twig_init(Object(Drupal\Core\Extension\Extension))
#3 /var/www/html/mysite.dev/web/core/lib/Drupal/Core/Theme/ThemeInitialization.php(144): call_user_func('twig_init', Object(Drupal\Core\Extension\Extension))
#4 /var/www/html/mysite.dev/web/core/lib/Drupal/Core/Theme/ThemeManager.php(122): Drupal\Core\Theme\ThemeInitialization->loadActiveTheme(Object(Drupal\Core\Theme\ActiveTheme))
#5 /var/www/html/mysite.dev/web/core/includes/theme.maintenance.inc(99): Drupal\Core\Theme\ThemeManager->setActiveTheme(Object(Drupal\Core\Theme\ActiveTheme))
#6 /var/www/html/mysite.dev/web/core/includes/bootstrap.inc(740): _drupal_maintenance_theme()
#7 /var/www/html/mysite.dev/web/core/includes/install.core.inc(493): drupal_maintenance_theme()
#8 /var/www/html/mysite.dev/web/core/includes/install.core.inc(114): install_begin_request(Object(Composer\Autoload\ClassLoader), Array)
#9 /var/www/html/mysite.dev/vendor/drupal/console/src/Command/Site/InstallCommand.php(542): install_drupal(Object(Composer\Autoload\ClassLoader), Array)
#10 /var/www/html/mysite.dev/vendor/drupal/console/src/Command/Site/InstallCommand.php(433): Drupal\Console\Command\Site\InstallCommand->runInstaller(Array, 'default')
#11 /var/www/html/mysite.dev/vendor/symfony/console/Command/Command.php(252): Drupal\Console\Command\Site\InstallCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/mysite.dev/vendor/symfony/console/Application.php(964): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/mysite.dev/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Site\InstallCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/mysite.dev/vendor/drupal/console-core/src/Application.php(185): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/mysite.dev/vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/mysite.dev/vendor/symfony/console/Application.php(148): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/mysite.dev/vendor/drupal/console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#18 /var/www/html/mysite.dev/vendor/drupal/console/bin/drupal(4): require('/var/www/html/m...')
#19 {main}
Error: Class &#039;Drupal\bootstrap\Bootstrap&#039; not found in include_once() (line 31 of /var/www/html/mysite.dev/web/themes/contrib/bootstrap/bootstrap.theme).
```

### Solution

No known command-line workaround

**Comment by nequeteme** [comment]
I @zenlan, I tested with Console version 1.9.0 and I can reproduce, but after adding the theme bootstrap to the themename.info.yml the installation works, and I add the boostrap_subtheme and bootstrap to the folder profiles/myprofile/themes/
 
`themes:
  - bartik
  - seven
  - bootstrap
  - mybootstrap`

I looked this page http://www.thecarneyeffect.co.uk/creating-installation-profile
