### ISSUE TITLE
drupal generate:form

### ISSUE THREAD

**Issue by laurencefass** [hechoendrupal/drupal-console#3942]
[ *ISSUE-GROUP* ] Short description

console generate

### Problem/Motivation

error generating custom form.

```
> drupal generate:form

 // Welcome to the Drupal Form generator
 Enter the module name [admin_toolbar]:
 > myfirstmodule

 Enter the Form Class name [DefaultForm]:
 > myfirstForm

 Enter the Form id [myfirst_form]:
 >

 Do you want to load services from the container? (yes/no) [no]:
 >

 Do you want to generate a config file? (yes/no) [yes]:
 >

 Do you want to generate a form structure? (yes/no) [yes]:
 >

Available types: button, checkbox, checkboxes, color, date, datelist, datetime, email, entity_autocomplete, field_ui_table, fieldset, file, hidden, image_button, item,
language_configuration, language_select, machine_name, managed_file, number, password, password_confirm, path, radio, radios, range, search, select, submit, table, tableselect, tel, text_format, textarea, textfield, token, url, value, webform_address, webform_audio_file, webform_autocomplete, webform_buttons, webform_buttons_other, webform_checkbox_value, webform_checkboxes_other, webform_codemirror, webform_computed_token, webform_computed_twig, webform_contact, webform_custom_composite, webform_document_file, webform_element_attributes, webform_element_composite, webform_element_multiple, webform_element_options, webform_element_states, webform_email_confirm, webform_email_multiple, webform_entity_checkboxes, webform_entity_radios, webform_entity_select, webform_excluded_columns, webform_excluded_elements, webform_html_editor, webform_image_file, webform_image_resolution, webform_likert, webform_link, webform_location_geocomplete, webform_location_places, webform_mapping, webform_multiple, webform_name, webform_options, webform_permissions, webform_radios_other, webform_rating, webform_roles, webform_select_other, webform_signature, webform_submission_views, webform_submission_views_replace, webform_table_sort, webform_tableselect_sort, webform_telephone, webform_term_checkboxes, webform_term_select, webform_terms_of_service, webform_time, webform_toggle, webform_toggles, webform_users, webform_video_file, weight

 Enter a new field properties

 New field type (press <return> to stop adding fields) []:
 > email
 Input label:
 > email
 Input machine name [email]:
 >
 Description []:
 >
 Default value []:
 > default@email.com
 Weight for input item [0]:
 >
 Enter a new field properties
 New field type (press <return> to stop adding fields) []:
 >
 Enter the route path [/myfirstmodule/form/myfirst]:
 >
 // router:rebuild
Rebuilding routes, wait a moment please
ParseError: syntax error, unexpected 'default' (T_DEFAULT) in /var/www/html/web/modules/custom/myfirstmodule/src/Form/myfirstForm.php on line 28 #0 /var/www/html/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/var/www/html/w...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Drupal\\myfirstm...')
#2 [internal function]: spl_autoload_call('Drupal\\myfirstm...')
#3 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityResolverManager.php(72): class_exists('\\Drupal\\myfirst...')
#4 /var/www/html/web/core/lib/Drupal/Core/Entity/EntityResolverManager.php(206): Drupal\Core\Entity\EntityResolverManager->getControllerClass(Array)
#5 /var/www/html/web/core/lib/Drupal/Core/EventSubscriber/EntityRouteAlterSubscriber.php(48): Drupal\Core\Entity\EntityResolverManager->setRouteOptions(Object(Symfony\Component\Routing\Route))
#6 [internal function]: Drupal\Core\EventSubscriber\EntityRouteAlterSubscriber->onRoutingRouteAlterSetType(Object(Drupal\Core\Routing\RouteBuildEvent), 'routing.route_a...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#7 /var/www/html/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Drupal\Core\Routing\RouteBuildEvent), 'routing.route_a...', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#8 /var/www/html/web/core/lib/Drupal/Core/Routing/RouteBuilder.php(184): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('routing.route_a...',
Object(Drupal\Core\Routing\RouteBuildEvent))
#9 /var/www/html/web/core/lib/Drupal/Core/ProxyClass/Routing/RouteBuilder.php(83): Drupal\Core\Routing\RouteBuilder->rebuild()
#10 /var/www/html/vendor/drupal/console/src/Command/Router/RebuildCommand.php(48): Drupal\Core\ProxyClass\Routing\RouteBuilder->rebuild()
#11 /var/www/html/vendor/symfony/console/Command/Command.php(255): Drupal\Console\Command\Router\RebuildCommand->execute(Object(Symfony\Component\Console\Input\ArrayInput), Object(Drupal\Console\Core\Style\DrupalStyle))
#12 /var/www/html/vendor/drupal/console-core/src/EventSubscriber/CallCommandListener.php(76): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArrayInput), Object(Drupal\Console\Core\Style\DrupalStyle))
#13 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Drupal\Console\Core\EventSubscriber\CallCommandListener->callCommands(Object(Symfony\Component\Console\Event\ConsoleTerminateEvent), 'console.termina...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 /var/www/html/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'console.termina...', Object(Symfony\Component\Console\Event\ConsoleTerminateEvent))
#15 /var/www/html/vendor/symfony/console/Application.php(991): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('console.termina...', Object(Symfony\Component\Console\Event\ConsoleTerminateEvent))
#16 /var/www/html/vendor/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(Drupal\Console\Command\Generate\FormBaseCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/drupal/console-core/src/Application.php(185): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(148): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/drupal/console/bin/drupal.php(89): Symfony\Component\Console\Application->run()
#21 /var/www/html/vendor/drupal/console/bin/drupal(4): require('/var/www/html/v...')
#22 {main}
ParseError: syntax error, unexpected &#039;default&#039; (T_DEFAULT) in Composer\Autoload\includeFile() (line 28 of /var/www/html/web/modules/custom/myfirstmodule/src/Form/myfirstForm.php).

**Details to include:**
- Drupal version : latest
- Console version : latest
```

**Comment by LOBsTerr** [comment]
Default value wasn't wrapped into quotes.
PR - https://github.com/hechoendrupal/drupal-console/pull/3944

**Comment by laurencefass** [comment]
thanks for reply.

so 

Default value []:
> "default@email.com"

is correct?

**Comment by LOBsTerr** [comment]
@laurencefass If you want to fix your current form, then yes - it is a fix. In the future versions it will be done automatically

**Comment by LOBsTerr** [comment]
It was merged
