### ISSUE TITLE
[ERROR] Class Drupal\Core\DrupalKernel does not exist.

### ISSUE THREAD

**Issue by liquidcms** [hechoendrupal/drupal-console#4207]
### Issue title

The *ISSUE-GROUP* should be one of:
* `console`

### Problem/Motivation
When running Drupal console i get: [ERROR] Class Drupal\Core\DrupalKernel does not exist.
 as well as:
Drupal Console version 1.9.4
and usage hints as well as command summary; although command summary is not correct list of commands

**Details to include:**
- Why are we doing this? Above all, a summary should explain why a change is needed, in a few short sentences.

### How to reproduce
from drupal root folder:
vendor/bin/drupal

**Details to include:**
- Drupal version: 8.7.10
- Console version: 1.9.4
- Console Launcher version: n/a
- OS: Windows 7

Working version Drupal 8.7.10 install. To stat fresh (because composer dependencies preventing me from installing console)
- delete composer.lock
- delete /vendors folder
- only thing in composer.json is require line for drush
- install console:
composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader --sort-packages

- drush works
- drupal site works

TEST:
vendor\bin\drupal site:status

 [ERROR] Class Drupal\Core\DrupalKernel does not exist.

 [ERROR] Command "site:status", is not a valid command name.

### Solution
??

**Comment by iwzkid** [comment]
Install Drupal console per project and either export the project's vendor path to bash or use this path `vendor/drupal/console/bin/drupal site:status`
This has worked for me for 3 sites, all with the same error.

**Comment by SilverWhitefish** [comment]
```
./drupal 

                                                                                                                        
 [ERROR] Class Drupal\Core\DrupalKernel does not exist.                                                                 
                                                                                                                        

PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "console.configuration_manager". in WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php:1060
Stack trace:
#0 WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php(620): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition()
#1 WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#2 WEB-ROOT/modules/custom/console/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(79): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#3 WEB-ROOT/modules/custom/console/src/Bootstrap/Drupal.php(284): Drupal\Console\Core\Bootstrap\DrupalConsoleCore->boot()
#4 WEB-ROOT/modules/custom/co in WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1060

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "console.configuration_manager". in WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php:1060
Stack trace:
#0 WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php(620): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition()
#1 WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#2 WEB-ROOT/modules/custom/console/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(79): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#3 WEB-ROOT/modules/custom/console/src/Bootstrap/Drupal.php(284): Drupal\Console\Core\Bootstrap\DrupalConsoleCore->boot()
#4 WEB-ROOT/modules/custom/co in WEB-ROOT/modules/custom/console/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1060
```

**Comment by SilverWhitefish** [comment]
```
./drupal 

                                                                                                                        
 [ERROR] Class Drupal\Core\DrupalKernel does not exist.                                                                 
                                                                                                                        

PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "console.configuration_manager". in WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php:1060
Stack trace:
#0 WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php(620): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition()
#1 WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#2 WEB-ROOT/modules/contrib/console/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(79): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#3 WEB-ROOT/modules/contrib/console/src/Bootstrap/Drupal.php(284): Drupal\Console\Core\Bootstrap\DrupalConsoleCore->boot()
#4 WEB-ROOT/modules/cont in WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1060

Fatal error: Uncaught Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "console.configuration_manager". in WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php:1060
Stack trace:
#0 WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php(620): Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition()
#1 WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php(588): Symfony\Component\DependencyInjection\ContainerBuilder->doGet()
#2 WEB-ROOT/modules/contrib/console/vendor/drupal/console-core/src/Bootstrap/DrupalConsoleCore.php(79): Symfony\Component\DependencyInjection\ContainerBuilder->get()
#3 WEB-ROOT/modules/contrib/console/src/Bootstrap/Drupal.php(284): Drupal\Console\Core\Bootstrap\DrupalConsoleCore->boot()
#4 WEB-ROOT/modules/cont in WEB-ROOT/modules/contrib/console/vendor/symfony/dependency-injection/ContainerBuilder.php on line 1060

```
