### ISSUE TITLE
[ *console* ] `drupal cr` triggers a fatal uncaught error

### ISSUE THREAD

**Issue by bkline** [hechoendrupal/drupal-console#4261]
### Problem/Motivation
The issue was filed because clearing the Drupal cache is an essential part of a Drupal developer's workday.

### How to reproduce
Here are the steps which led to the failure.

1. install fresh Drupal 9.3
2. install Drupal Console 1.9.5
3. create and enable a custom module
4. run `../vendor/bin/drupal deco ...`
5. run `../vendor/bin/drupal cr`
6. see stack trace

```
 Rebuilding cache(s), wait a moment please.
PHP Fatal error:  Uncaught Error: Call to undefined method Drupal\Core\DrupalKernel::prepareLegacyRequest() in /var/www/ebms/vendor/drupal/console/src/Utils/DrupalApi.php:266
Stack trace:
#0 /var/www/ebms/vendor/drupal/console/src/Command/Cache/RebuildCommand.php(104): Drupal\Console\Utils\DrupalApi->drupal_rebuild()
#1 /var/www/ebms/vendor/symfony/console/Command/Command.php(255): Drupal\Console\Command\Cache\RebuildCommand->execute()
#2 /var/www/ebms/vendor/symfony/console/Application.php(1018): Symfony\Component\Console\Command\Command->run()
#3 /var/www/ebms/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#4 /var/www/ebms/vendor/drupal/console-core/src/Application.php(187): Symfony\Component\Console\Application->doRun()
#5 /var/www/ebms/vendor/drupal/console/src/Application.php(64): Drupal\Console\Core\Application->doRun()
#6 /var/www/ebms/vendor/symfony/console/Application.php(147): Drupal\Console\Application->doRun()
#7 /var/www/ebms/vendor/drupal/console/bin/drupal.php( in /var/www/ebms/vendor/drupal/console/src/Utils/DrupalApi.php on line 266

Fatal error: Uncaught Error: Call to undefined method Drupal\Core\DrupalKernel::prepareLegacyRequest() in /var/www/ebms/vendor/drupal/console/src/Utils/DrupalApi.php on line 266

Error: Call to undefined method Drupal\Core\DrupalKernel::prepareLegacyRequest() in /var/www/ebms/vendor/drupal/console/src/Utils/DrupalApi.php on line 266

Call Stack:
    0.0006     388240   1. {main}() /var/www/ebms/vendor/drupal/console/bin/drupal:0
    0.0020     401312   2. require('/var/www/ebms/vendor/drupal/console/bin/drupal.php') /var/www/ebms/vendor/drupal/console/bin/drupal:4
    9.1764   22630160   3. Drupal\Console\Application->run() /var/www/ebms/vendor/drupal/console/bin/drupal.php:89
    9.1775   22636480   4. Drupal\Console\Application->doRun() /var/www/ebms/vendor/symfony/console/Application.php:147
   14.5769   31447080   5. Drupal\Console\Application->doRun() /var/www/ebms/vendor/drupal/console/src/Application.php:64
   15.1642   39527336   6. Drupal\Console\Application->doRun() /var/www/ebms/vendor/drupal/console-core/src/Application.php:187
   15.1645   39528408   7. Drupal\Console\Application->doRunCommand() /var/www/ebms/vendor/symfony/console/Application.php:271
```

### Solution
Avoid calling undefined methods.

**Comment by chriswales95** [comment]
Can second this. Just came across this myself when running a fresh install of Drupal 9 and installing Drupal Console.

**Comment by ben74** [comment]
Same here .. fresh d9 install + drupal console .. hit on this error while rebuilding caches

**Comment by flashvnn** [comment]
Same here, i temporary remove code at line vendor/drupal/console/src/Utils/DrupalApi.php:266
```
$kernel->prepareLegacyRequest($request);
```
Drupal console work for now but need official update.

**Comment by dhallek** [comment]
Same problem here. The workaround of @flashvnn seems to fix it.

**Comment by devagit** [comment]
Same here: Drupal Console 1.9.5, Drupal Core 9.0.7

**Comment by santiagoyie** [comment]
I had the same error, but running drupal site:mode dev with Drupal Console version 1.9.7 and Drupal core 9.0.3.
The workaround of @flashvnn seems to fix it for me too.

**Comment by zietbukuel** [comment]
I'm also having the same issue with Drupal 9.1.0 and Drupal Console 1.9.7.

**Comment by jvanbiervliet** [comment]
Same Drupal 9.1.0 Drupal Console 1.9.7
What's up with this ?

**Comment by DigitalSolace** [comment]
Same with Drupal Core 9.1.2 , Drupal Console 1.79.7.

**Comment by DerH4NNES** [comment]
Same with Drupal Core 9.1.3, 1.9.7

**Comment by devkinetic** [comment]
[DrupalKernelInterface::prepareLegacyRequest](https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21DrupalKernelInterface.php/function/DrupalKernelInterface%3A%3AprepareLegacyRequest/8.9.x).

> Deprecated
in drupal:8.0.0 and is removed from drupal:9.0.0. Use DrupalKernel::boot() and DrupalKernel::preHandle() instead.

**Comment by acnimda** [comment]
> 
> 
> Same here, i temporary remove code at line vendor/drupal/console/src/Utils/DrupalApi.php:266
> 
> ```
> $kernel->prepareLegacyRequest($request);
> ```
> 
> Drupal console work for now but need official update.

@flashvnn This did work for me on latest drupal 9 version. 
- go to `vendor/drupal/console/src/Utils/DrupalApi.php`
uncomment somehwere around line 265:
` // Prepare a NULL request.`
 `// $kernel->prepareLegacyRequest($request);`

 `prepareLegacyRequest(Request $request)` didn't solve the issue.

**Comment by petiar** [comment]
It looks like there's more deprecated functions in the Drupal console codebase.

For fixing the `drupal cr` command you need to replace the line 266 (the one with the `prepareLegacyRequest()` call with following lines:
```
$kernel->boot();
$kernel->preHandle($request);
```
There is also a PR for this, it's #4269 

To fix the `drupal moi` command replace the line 178 (the one with the `system_rebuild_module_data()` call) in the `src/Command/Shared/ProjectDownloadTrait.php` with following:
```
$moduleList = \Drupal::service("extension.list.module")->getList();
```

**Comment by acnimda** [comment]
> 
> 
> It looks like there's more deprecated functions in the Drupal console codebase.
> 
> For fixing the `drupal cr` command you need to replace the line 266 (the one with the `prepareLegacyRequest()` call with following lines:
> 
> ```
> $kernel->boot();
> $kernel->preHandle($request);
> ```
> 
> There is also a PR for this, it's #4269
> 
> To fix the `drupal moi` command replace the line 178 (the one with the `system_rebuild_module_data()` call) in the `src/Command/Shared/ProjectDownloadTrait.php` with following:
> 
> ```
> $moduleList = \Drupal::service("extension.list.module")->getList();
> ```

Alright this works, great work!

**Comment by MurzNN** [comment]
Thanks, PR #4269 fixes that error! But why it is not merged yet almost year already?

**Comment by BramDriesen** [comment]
Would be great to see this one getting fixed and closed...

**Comment by RSickenberg** [comment]
The PR has been approved but no news on this 😔

**Comment by bkline** [comment]
If this project isn't dead, it's showing all the signs of being in a coma. 😉
