### ISSUE TITLE
[cache:rebuild] Exception thrown on cache:rebuild on a Drupal 9 project

### ISSUE THREAD

**Issue by hron84** [hechoendrupal/drupal-console#4298]
### Problem/Motivation
I tried to run drupal `cache:rebuild` on a Drupal 9 project, and it failed.

### How to reproduce

**Details to include:**
- Drupal version 9.1.5
- Console version 1.9.7
- Console Launcher version 1.9.7

I created a sample site with `drupal/recommended-project:^9.0` project template and installed `drupal/console:1.9.7` into the profile. I installed the site (with drush), and I wanted to test `cache:rebuild` command. This is what I get:

```
$ drupal cr

 Rebuilding cache(s), wait a moment please.
PHP Fatal error:  Uncaught Error: Call to undefined method Drupal\Core\DrupalKernel::prepareLegacyRequest() in /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Utils/DrupalApi.php:266
Stack trace:
#0 /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Command/Cache/RebuildCommand.php(104): Drupal\Console\Utils\DrupalApi->drupal_rebuild()
#1 /home/hron/Projects/job/macroweb/d9test/vendor/symfony/console/Command/Command.php(255): Drupal\Console\Command\Cache\RebuildCommand->execute()
#2 /home/hron/Projects/job/macroweb/d9test/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()
#3 /home/hron/Projects/job/macroweb/d9test/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console-core/src/Application.php(187): Symfony\Component\Console\Application->doRun()
#5 /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Application.php(64): Drupal\Cons in /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Utils/DrupalApi.php on line 266

Fatal error: Uncaught Error: Call to undefined method Drupal\Core\DrupalKernel::prepareLegacyRequest() in /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Utils/DrupalApi.php:266
Stack trace:
#0 /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Command/Cache/RebuildCommand.php(104): Drupal\Console\Utils\DrupalApi->drupal_rebuild()
#1 /home/hron/Projects/job/macroweb/d9test/vendor/symfony/console/Command/Command.php(255): Drupal\Console\Command\Cache\RebuildCommand->execute()
#2 /home/hron/Projects/job/macroweb/d9test/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run()
#3 /home/hron/Projects/job/macroweb/d9test/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#4 /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console-core/src/Application.php(187): Symfony\Component\Console\Application->doRun()
#5 /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Application.php(64): Drupal\Cons in /home/hron/Projects/job/macroweb/d9test/vendor/drupal/console/src/Utils/DrupalApi.php on line 266
```

**Comment by LOBsTerr** [comment]
fixed in 1.9.8
